name: Publish to NPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install WASM-Pack
        run: "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
      - name: Login
        run: "echo -e \"$USERNAME\n$TOKEN\n$USERNAME_EMAIL\n\" wasm-pack login -r=https://npm.pkg.github.com -s=@umgefahren"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          USERNAME_EMAIL: "55623006+umgefahren@users.noreply.github.com"
      - name: Build
        run: "wasm-pack build"
      - name: Pack
        run: "wasm-pack pack"
      - name: Copy package.json
        run: "cp package.json pkg/."
      - name: Publish WASM-Pack
        run: "wasm-pack publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}