name: Publish to NPM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install WASM-Pack
        run: "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Login
        run: "wasm-pack login"
      - name: Build
        run: "wasm-pack build"
      - name: Pack
        run: "wasm-pack pack"
      - name: Publish WASM-Pack
        run: "wasm-pack publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}